[default]
path   = "/"
color  = "#31AF31"

[index]
path   = "/bonsai/index/"
prefix = "i."
emoji  = "ğŸ—„"
color  = "#F0C61F"
# emoji  = "ğŸªµ" ; bonsai.trunk

[entry]
path   = "/bonsai/entries/"
emoji  = "ğŸ·"
color  = "#31AF31"
# emoji  = "ğŸƒ"; bonsai.leaf

[book]
path   = "/book/"
prefix = "bk."
emoji  = "ğŸ“š"
